services:
  bimbly-postgres:
    image: postgres:15-alpine
    container_name: bimbly-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bimbly-network

  bimbly-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bimbly-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - bimbly-postgres
    restart: unless-stopped
    networks:
      - bimbly-network

volumes:
  postgres_data:

networks:
  bimbly-network:
    external: true
